#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-.}")/.." && pwd)"
cd "$REPO_ROOT"

REPO_OWNER="Odin94"
REPO_NAME="cutest-disk-tree"
GITHUB_RELEASES_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases"

echo "=== Cutest Disk Tree – Release script ==="
echo "Repo root: $REPO_ROOT"
echo ""

if [[ -z "${RELEASE_SKIP_CONFIRM:-}" ]]; then
  echo "Before continuing, please confirm:"
  echo "  1. You have bumped the version in src-tauri/tauri.conf.json (and package.json if you use it for display)."
  echo "  2. You have run 'npm install' and dependencies are up to date."
  echo "  3. This is the ${REPO_OWNER}/${REPO_NAME} repo (releases will point to GitHub)."
  echo "  4. You have already run a signed build (npm run tauri build with TAURI_SIGNING_PRIVATE_KEY set)."
  echo ""
  read -p "Have you done all of the above? (y/N) " -n 1 -r
  echo
  if [[ ! "${REPLY,,}" =~ ^y ]]; then
    echo "Stopping. Complete the steps above and run this script again."
    echo ""
    echo "To build with signing before re-running this script:"
    echo "  export TAURI_SIGNING_PRIVATE_KEY=\"\$(cat .tauri-private-key | base64 -d 2>/dev/null || cat .tauri-private-key | base64 -D)\""
    echo "  npm run tauri build"
    exit 1
  fi
fi

if [[ ! -f ".tauri-private-key" ]] || [[ ! -f ".tauri-public-key" ]]; then
  echo "Error: .tauri-private-key and .tauri-public-key must exist in the repo root."
  exit 1
fi

PRIVATE_KEY_B64="$(cat .tauri-private-key)"
PUBLIC_KEY_B64="$(cat .tauri-public-key)"
TAURI_PRIVATE_KEY="$(echo "$PRIVATE_KEY_B64" | base64 -d 2>/dev/null || echo "$PRIVATE_KEY_B64" | base64 -D 2>/dev/null)"
TAURI_PUBLIC_KEY="$(echo "$PUBLIC_KEY_B64" | base64 -d 2>/dev/null || echo "$PUBLIC_KEY_B64" | base64 -D 2>/dev/null)"

if [[ -z "$TAURI_PUBLIC_KEY" ]]; then
  echo "Error: Could not decode .tauri-public-key (expected base64)."
  exit 1
fi

CONF_JSON="src-tauri/tauri.conf.json"
PUBKEY_FILE="${REPO_ROOT}/.tauri-public-key.decoded"
echo "$TAURI_PUBLIC_KEY" > "$PUBKEY_FILE"
trap 'rm -f "$PUBKEY_FILE"' EXIT
echo "Patching $CONF_JSON with public key and endpoint..."
node scripts/patch-updater-config.cjs
rm -f "$PUBKEY_FILE"
trap - EXIT

VERSION="$(node -e "console.log(JSON.parse(require('fs').readFileSync('$CONF_JSON','utf8')).version)")"
TAG="v${VERSION}"
BUNDLE_DIR="src-tauri/target/release/bundle"
OUT_DIR="release-out/${TAG}"
mkdir -p "$OUT_DIR"

if [[ ! -d "$BUNDLE_DIR" ]]; then
  echo "Error: Bundle directory not found: $BUNDLE_DIR"
  echo "Run a signed build first (see step 4 in the pre-steps), then run this script again."
  exit 1
fi

SIG_PATHS_FILE="${OUT_DIR}/.sigpaths"
find "$BUNDLE_DIR" -name "*.sig" -type f 2>/dev/null > "$SIG_PATHS_FILE" || true
if [[ ! -s "$SIG_PATHS_FILE" ]]; then
  echo "Warning: No .sig files found under $BUNDLE_DIR. You may need to run the build with TAURI_SIGNING_PRIVATE_KEY set."
fi

PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Building latest.json..."
node scripts/generate-latest-json.cjs "$SIG_PATHS_FILE" "$OUT_DIR" "$VERSION" "$PUB_DATE" "$TAG"
rm -f "$SIG_PATHS_FILE"

{
  echo "Files to upload to GitHub Release ${TAG}:"
  echo ""
  echo "--- Built artifacts (from this machine) ---"
  find "$BUNDLE_DIR" -type f \( -name "*.exe" -o -name "*.msi" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.tar.gz" \) ! -name "*.sig" 2>/dev/null || true
  find "$BUNDLE_DIR" -type f -name "*.sig" 2>/dev/null || true
  echo ""
  echo "--- Generated by this script ---"
  echo "${OUT_DIR}/latest.json"
  echo ""
  echo "--- For other platforms (build on each OS, then upload the same types) ---"
  echo "  Windows: .exe or .msi + matching .sig (e.g. from bundle/nsis/ or bundle/msi/)"
  echo "  macOS:   .dmg or .app.tar.gz + matching .sig (e.g. from bundle/dmg/ or bundle/macos/)"
  echo "  Linux:   .AppImage or .deb + matching .sig (e.g. from bundle/appimage/ or bundle/deb/)"
} > "${OUT_DIR}/manifest.txt"
cat "${OUT_DIR}/manifest.txt"

echo ""
echo "=== Manual steps (no uploads were performed) ==="
echo ""
echo "1. Open: ${GITHUB_RELEASES_URL}/new"
echo "2. Create a new release with tag: ${TAG}"
echo "   (create the tag if it does not exist)."
echo "3. Upload all installer and .sig files listed in: ${OUT_DIR}/manifest.txt"
echo "   (from the paths shown above; typically under src-tauri/target/release/bundle/)."
echo "4. Upload this file as an asset named exactly: latest.json"
echo "   Path: ${OUT_DIR}/latest.json"
echo "5. Publish the release."
echo ""
echo "After publishing, the in-app \"Check for updates\" will use:"
echo "  ${GITHUB_RELEASES_URL}/latest/download/latest.json"
echo ""
